Assignment 1 (due on 10/25)  
学生：胡蓓慧 (12332288)，Github: beihuihu  
批改人：Zhao Shuhui  
得分：94/100  

# PS1_1 
5/10  
1.创建了Print_values(a,b,c)方法 √  
2.4种输出情况都能满足   -5  算法有误  
3.报告里列出部分例子（此项本次不扣分仅提醒）    √

In [2]:
# %load PS1_1.py
"""
Created on Sun Oct 22 19:11:33 2023

@author: 22948
"""
import random as random
def Print_values(a,b,c):
    if a>b:
        if b>c:
            if a>c:
                print("output:{} {} {}".format(a,c,b))
            else:
                print("output:{} {} {}".format(c,a,b))
        else:
            print("output:{} {} {}".format(a,b,c))
    else:
        if not b>c:
            print("output:{} {} {}".format(c,b,a))
        
a=random.random()
print("a:{}".format(a))
b=random.random()
print("b:{}".format(b))
c=random.random()
print("c{}".format(c))
Print_values(a,b,c)

a:0.3310516820592728
b:0.1513808202909145
c0.19731020560356216
output:0.3310516820592728 0.1513808202909145 0.19731020560356216


In [5]:
# TA corrected
def Print_values(a,b,c):
    if a>b:
        if b>c:
            print("output:{} {} {}".format(a,b,c))
        else:
            if a>c:
                print("output:{} {} {}".format(a,c,b))
            else:
                print("output:{} {} {}".format(c,a,b))
    else:
        if not b>c:
            print("output:{} {} {}".format(c,b,a))

# PS1_2
15/15  
1.能自行创建矩阵M1(5行10列)和M2(10行5列)    √  
2.M1, M2的数值范围为0到50的整数 √  
3.创建能进行矩阵乘法的方法Matrix_multip()   √  
4.方法内仅使用for循环, *和+运算符   √  
5.报告里列出部分例子（此项本次不扣分仅提醒）    √

In [8]:
# %load PS1_2.py
"""
Created on Sun Oct 22 23:51:17 2023

@author: 22948
"""
import numpy as np
M1=np.random.randint(0,51,(5,10))
M2=np.random.randint(0,51,(10,5))
print("M1:{}".format(M1))
print("M2:{}".format(M2))

def Matrix_multip(M1,M2):
    if M1.shape[1]!=M2.shape[0]:
        return "error"
    else:
        row=M1.shape[0]
        col=M2.shape[1]
        middle=M1.shape[1]
        M3=np.zeros((row,col))
        for i in range(0,row):
            for j in range(0,col):
                for k in range(0,middle):
                    M3[i,j]+=M1[i,k]*M2[k,j]
    return M3
    
print("M1*M2:{}".format(Matrix_multip(M1,M2)))

M1:[[39  7 33 13 47 30 13 33  1  0]
 [45 41  8 35 30 47 40  3 22 24]
 [44  6 49 30  7 24 16 39 46 46]
 [ 8 20  7 43  7  0 31 30 11 10]
 [13 24 23 15  1 44 32 50 32 20]]
M2:[[41 12  4  6 23]
 [46 42 31  9 35]
 [ 1 17 20 16  9]
 [13 42 41 38 21]
 [19 38 37 29  2]
 [23 17  1 18  5]
 [39 41  8 33 42]
 [17  2 16 47 24]
 [29 33  7 25 35]
 [17 42 45  1 34]]
M1*M2:[[4803. 4797. 3974. 5227. 3329.]
 [8502. 9187. 5805. 5848. 6910.]
 [6607. 7731. 5999. 6434. 7209.]
 [4155. 5241. 4069. 4895. 4611.]
 [6252. 6279. 4132. 6279. 6227.]]


In [9]:
#TA test
print(np.matmul(M1,M2)==Matrix_multip(M1,M2))

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


# PS1_3
20/20  
1.创建了Pascal_triangle(k)方法  √  
2.能够输出第n行的Pascal_triangle    √  
3.报告里列出k=100和200的情况（此项本次不扣分仅提醒）    √

In [11]:
# %load PS1_3.py
"""
Created on Mon Oct 23 00:15:24 2023

@author: 22948
"""
def Pascal_triangle(k):
    List=[]
    for i in range(0,k):
        tempList=[]
        for j in range(0,i+1):
            if j==0 or j==i:
                tempList.append(1)
            else:
                tempList.append(List[i-1][j-1]+List[i-1][j])
        List.append(tempList)
    return List[-1]
        

print("line 100:{}".format(Pascal_triangle(100)))
print("line 200:{}".format(Pascal_triangle(200)))

line 100:[1, 99, 4851, 156849, 3764376, 71523144, 1120529256, 14887031544, 171200862756, 1731030945644, 15579278510796, 126050526132804, 924370524973896, 6186171974825304, 38000770702498296, 215337700647490344, 1130522928399324306, 5519611944537877494, 25144898858450330806, 107196674080761936594, 428786696323047746376, 1613054714739084379224, 5719012170438571889976, 19146258135816088501224, 60629817430084280253876, 181889452290252840761628, 517685364210719623706172, 1399667836569723427057428, 3599145865465003098147672, 8811701946483283447189128, 20560637875127661376774632, 45764000431735762419272568, 97248500917438495140954207, 197443926105102399225573693, 383273503615787010261407757, 711793649572175876199757263, 1265410932572757113244012912, 2154618614921181030658724688, 3515430371713505892127392912, 5498493658321124600506947888, 8247740487481686900760421832, 11868699725888281149874753368, 16390109145274293016493707032, 21726423750712434928840495368, 27651812046361280818524266832, 337

# PS1_4
20/20  
1.创建了Least_moves(x)方法  √  
2.方法能满足题目要求，且把结果print出来 √  
3.报告里列出部分例子（此项本次不扣分仅提醒）    √

In [20]:
# %load PS1_4.py
"""
Created on Mon Oct 23 00:46:08 2023

@author: 22948
"""
import math
import random
x=random.randint(1,101)
def Least_moves(RMB):
    step=0
    while RMB!=1:
        if RMB%2==1:
            step+=1
            RMB-=1
        else:
            step+=1
            RMB/=2
    return step
print(x)
print("step numbers:{}".format(Least_moves(x)))

54
step numbers:8


# PS1_5
34/35  
思路很独特！  
1.创建了Find_expression(x)方法  √  
2.方法满足题目要求，可以计算1到100的所有可能性组合，数字保持顺序    √  
3.将所有可能性组合数放到名为Total_solutions的list里，并plot，找出可能性组合数最多和最少的数 -1  未将Total_solutions给plot出来  
4.报告里列出部分例子（此项本次不扣分仅提醒）    √  

In [30]:
# %load PS1_5.py
"""
Created on Mon Oct 23 00:59:45 2023

@author: 22948
"""

def Find_expression(i,sum,index):
    global total_num
    if i==index+1:
        if sum==target_sum:
            result=""
            total_num+=1
            for j in range(0,index+1):
                result+=str(num[j])
                if j!=index:
                    if flag[j]:
                        result+="-"
                    else:
                        result+="+"
                else:
                    result+="={}".format(sum)
                    print(result)
        return
    elif i==0:
        Find_expression(i+1,num[i],index)
        return
    flag[i-1]=0
    Find_expression(i+1,sum+num[i],index)
    flag[i-1]=1
    Find_expression(i+1,sum-num[i],index)
    return
        
    
#n 分成几个数 r剩几个数
def generate_num(n,r,index,now_num):
    if n==1:
        for i in range(-r,0):
            num[index]=num[index]*10+now_num
            now_num+=1
        Find_expression(0,0,index)
        num[index]=0
        now_num=r-n+1
        return
    else:
        #至多可以与后面 r-n 个数字结合
        for i in range(0,r-n+1):
            for j in range(0,i+1):
                num[index]=num[index]*10+now_num
                now_num+=1
            index+=1
            generate_num(n-1,r-i-1,index,now_num)
            index-=1
            num[index]=0
            now_num-=i+1
            
num=[0,0,0,0,0,0,0,0,0]
now_num=1
index=0 #分成的第几个数
flag=[0,0,0,0,0,0,0,0]
target_sum=50
total_num=0
#5.1
for n in range(9,1,-1):
   generate_num(n,9,index,now_num)
   


1-2-3-4-5-6+78-9=50
1+2+3-4+56-7+8-9=50
1+2-3+4+56+7-8-9=50
1-2-3+4+56-7-8+9=50
1+2+34-5-6+7+8+9=50
1-2+34+5+6+7+8-9=50
1+2+3+4-56+7+89=50
1-2+3-45+6+78+9=50
1+2-34+5-6-7+89=50
1-2-34-5-6+7+89=50
1-23+4+5-6+78-9=50
1-23-4-5-6+78+9=50
12-3-4-5+67-8-9=50
12-3+45+6+7-8-9=50
1-2+34-5-67+89=50
1+2+34-56+78-9=50
12+3+4-56+78+9=50


In [31]:
#5.2
Total_solutions=[]
for target_sum in range(1,101):
    total_num=0
    for n in range(9,1,-1):
        generate_num(n,9,index,now_num)
    Total_solutions.append(total_num)
Max=max(Total_solutions)
Min=min(Total_solutions)
def  searchIndex(List,num):
    resultList=[]
    for i in range(len(List)):
        if List[i]==num:
            resultList.append(i+1)
    return resultList
print("Total_solutions:")
print(Total_solutions)
print("{} yields the maximum of Total_solutions".format(searchIndex(Total_solutions,Max)))
print("{} yields the minimum of Total_solutions".format(searchIndex(Total_solutions,Min)))
    

1+2+3+4+5-6-7+8-9=1
1+2+3+4-5+6+7-8-9=1
1+2+3-4-5-6-7+8+9=1
1+2-3+4-5-6+7-8+9=1
1+2-3-4+5+6-7-8+9=1
1+2-3-4+5-6+7+8-9=1
1-2+3+4-5+6-7-8+9=1
1-2+3+4-5-6+7+8-9=1
1-2+3-4+5+6-7+8-9=1
1-2-3+4+5+6+7-8-9=1
1-2-3-4+5-6-7+8+9=1
1-2-3-4-5+6+7-8+9=1
1+23-4-5-6-7+8-9=1
1-23+4+5+6+7-8+9=1
1+2+3+45-67+8+9=1
1-2-3-45+67-8-9=1
1+2-34+56-7-8-9=1
1-2+34-56+7+8+9=1
12-34+5-6+7+8+9=1
1+23+4-5+67-89=1
1-23-4+5-67+89=1
1+23+45-67+8-9=1
1-23-45+67-8+9=1
12+34+5-67+8+9=1
1+23-45-67+89=1
1-23+45+67-89=1
1+2+34-5-6-7-8-9=2
12+3+4-5-6-7-8+9=2
12+3-4+5-6-7+8-9=2
12+3-4-5+6+7-8-9=2
12-3+4+5-6+7-8-9=2
12-3-4-5-6+7-8+9=2
1-2+34+56-78-9=2
1+23+4+56+7-89=2
12+3+4+5+67-89=2
123+4-56-78+9=2
123-45+6+7-89=2
1+2+3+4+5-6-7-8+9=3
1+2+3+4-5+6-7+8-9=3
1+2+3-4+5+6+7-8-9=3
1+2-3+4-5-6-7+8+9=3
1+2-3-4+5-6+7-8+9=3
1+2-3-4-5+6+7+8-9=3
1-2+3+4-5-6+7-8+9=3
1-2+3-4+5+6-7-8+9=3
1-2+3-4+5-6+7+8-9=3
1-2-3+4+5+6-7+8-9=3
1-2-3-4-5+6-7+8+9=3
1+23+4+5-6-7-8-9=3
1+23-4-5-6-7-8+9=3
1-23+4+5+6-7+8+9=3
12-34-5+6+7+8+9=3
1+23-4+5+67-89=3
1+23+4